version: '3'

volumes:
  backdrop-files:
  backdrop-sites:
  backdrop-layouts:
  backdrop-modules:
  backdrop-themes:
  mariadb-data:

services:
  backdrop:
    build: ./backdrop
    restart: always
    links:
      - "backdrop-db:database"
    ports:
      - ${BACKDROP_PORT}:80
    volumes:
      - backdrop-files:/var/www/html/files
      - backdrop-sites:/var/www/html/sites
      - backdrop-layouts:/var/www/html/layouts
      - backdrop-modules:/var/www/html/modules
      - backdrop-themes:/var/www/html/themes
    environment:
      BACKDROP_DB_HOST    : "${BACKDROP_DB_HOST}"
      BACKDROP_DB_PORT    : "${BACKDROP_DB_PORT}"
      BACKDROP_DB_NAME    : "${BACKDROP_DB_NAME}"
      BACKDROP_DB_USER    : "${BACKDROP_DB_USER}"
      BACKDROP_DB_PASSWORD: "${BACKDROP_DB_USER_PASSWORD}"
    depends_on:
      - backdrop-db

  backdrop-db:
    image: mariadb:latest
    container_name: ${BACKDROP_DB_HOST}
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE     : "${BACKDROP_DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${BACKDROP_DB_ROOT_PASSWORD}"
      MYSQL_USER         : "${BACKDROP_DB_USER}"
      MYSQL_PASSWORD     : "${BACKDROP_DB_USER_PASSWORD}"
    expose:
      - 3306

